name: Sync Kaggle Notebook to GitHub

on:
  schedule:
    - cron: "0 * * * *"  # Vérifie chaque heure
  workflow_dispatch:  # Permet un lancement manuel

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Configure Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download Notebook from Kaggle
        run: kaggle kernels output VOTRE_KAGGLE_USERNAME/NOM_DU_NOTEBOOK -p notebook

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Mise à jour automatique depuis Kaggle" || echo "Pas de changements à committer"
          git push
